export default {
    "login": "HarrisonHemstreet",
    "id": 65803282,
    "node_id": "MDQ6VXNlcjY1ODAzMjgy",
    "avatar_url": "https://avatars.githubusercontent.com/u/65803282?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/HarrisonHemstreet",
    "html_url": "https://github.com/HarrisonHemstreet",
    "followers_url": "https://api.github.com/users/HarrisonHemstreet/followers",
    "following_url": "https://api.github.com/users/HarrisonHemstreet/following{/other_user}",
    "gists_url": "https://api.github.com/users/HarrisonHemstreet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/HarrisonHemstreet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/HarrisonHemstreet/subscriptions",
    "organizations_url": "https://api.github.com/users/HarrisonHemstreet/orgs",
    "repos_url": "https://api.github.com/users/HarrisonHemstreet/repos",
    "events_url": "https://api.github.com/users/HarrisonHemstreet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/HarrisonHemstreet/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Harrison Hemstreet",
    "company": "Younique",
    "blog": "https://harrisonhemstreet.herokuapp.com/#",
    "location": "Utah",
    "email": null,
    "hireable": true,
    "bio": null,
    "twitter_username": "TheHemstreet",
    "public_repos": 32,
    "public_gists": 0,
    "followers": 11,
    "following": 11,
    "created_at": "2020-05-23T06:02:13Z",
    "updated_at": "2021-06-27T22:41:16Z"
};
